version: '3.9'
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: zerodha-ui-container
    ports:
      - "3000:80"
    restart: unless-stopped